### ISSUE TITLE
Question: License of cloned project 

### ISSUE THREAD

**Issue by g41797** [Chemaclass/php-scaffolding#14]
Lot of thanks for your efforts

I created repo via "Use this template"
How I can add my own license to the project without violating your rights?
I found [an answer](https://opensource.stackexchange.com/questions/10532/license-description-for-repository-that-uses-a-template-under-mit-license)
Is it acceptable?
Could you please clarify this issue in README?

**Comment by Chemaclass** [comment]
Hi! Feel free to fork, clone, change the code as you want. Don't need to ask for permission for that.
It has a MIT license, you can remove the license and create your own as you please :)
